rootProject.name = "hexagonal"
include("ddd")
include("city")
include("city:adapter")
include("city:ddd")
include("city:application")
include("city:web-adapter")
include("city:persistence-adapter")
include("city:external-adapter")
include("city:api")
include("city:temp")
include("city:configuration")
include("city:domain")
include("order")
include("order:api")
include("order:domain")
include("account")
include("inventory")
include("order:application")
findProject(":order:application")?.name = "application"
